application: goristock
version: mem
runtime: python
api_version: 1

handlers:
## Favion url.
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  mime_type: image/x-icon

## admin_console
- url: /admin_console/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

## Appstats
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  secure: always
  login: admin

- url: /task
  script: main.py
  login: admin
- url: /task_stock
  script: main.py
  login: admin
- url: /cron_mail
  script: main.py
  login: admin
- url: /cron_mail_test
  script: main.py
  login: admin
- url: /flush
  script: main.py
  login: admin

## Main WSGI
- url: .*
  script: main.py
  #secure: always
  #login: admin

inbound_services:
- xmpp_message
- mail

builtins:
- appstats: on

derived_file_type:
- python_precompiled

admin_console:
  pages:
  - url: /stats
    name: "Appstats"
  - url: /admin_console/
    name: "Admin_console"

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (tests/.*)
 )$
