============================
grs 台灣股市股票股價擷取
============================

主要開發擷取台灣股市（TWSE）股價資料，資料來源 `證券交易所網站 <http://www.twse.com.tw/>`_ 。

-----------------------------
版本資訊
-----------------------------

:Authors: Toomore Chiang
:Version: 0.0.1x of 2012/03/10
:Python Version: Python 2.6-2.7

-----------------------------
Report Issue or get involved
-----------------------------

- Maillist → https://groups.google.com/group/goristock-dev
- Issues → https://github.com/toomore/goristock/issues
- Github → https://github.com/toomore/goristock/tree/grs_rewrite

-----------------------------
Quick Start
-----------------------------

簡單計算

::

    from grs import stock

    g = stock(2618)       # 擷取長榮航股價
    print g.MA(5)         # 計算五日均價與持續天數
    print g.MAV(5)        # 計算五日均量與持續天數


擷取 12 個月份資料

::

    g = stock(2618, 12)


輸出 CSV 檔

::

    g.out_putfile('/dev/shm/2618.csv')

-----------------------------
其他功能
-----------------------------

顯示台灣時間：TWTime
=============================

適用於其他時區查詢台灣當地時間。

::

    from grs import TWTime

    t = TWTime()
    t.now                 # 顯示台灣此刻時間
    t.localtime           # 顯示當地此刻時間


判斷台灣股市是否開市：twseopen
====================================

::

    from grs import twseopen
    from datetime import datetime

    t = twseopen()

    t.Dday(datetime.today())       # 判斷今天是否開市，回傳 True or False
    t.Dday(datetime(2012, 12, 22)) # 判斷 2012/12/22 是否開市
